name: Semgrep Publish

on: [workflow_dispatch]

permissions:
  id-token: write
  contents: read
  pull-requests: write
  actions: read
  deployments: write

jobs:
  Test-Rules:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      # This will output the results of the validation and exit with a
      # 0 for success and non-0 on error
      
      - name: Validate Rules
        shell: bash
        run: |
          docker run \
            -v .:/src \
            returntocorp/semgrep:latest \
            semgrep scan --validate --error --config /src/rules

      # This will run the test suite and output
      
      - name: Run Test Suite
        shell: bash
        run: |
          docker run \
            -v .:/src \
            returntocorp/semgrep \
            semgrep scan --test --error --time --json --quiet --config /src/rules /src/tests > output.json
        
      - name: Validate Test Suite
        shell: python
        run: |
          import json
          import sys
          data = {}
          with open("./output.json","r") as fp:
            data = json.load(fp)
          if len(data["config_missing_tests"]) > 0:
            print("ERROR: The following rules are missing assocaited tests:")
            for test in data["config_missing_tests"]:
              print(test)
            sys.exit(1)
            
